build: support aarch64/x86 build
    - Also use buildx instead docker to build image

Signed-off-by: Vicente Cheng <vicente.cheng@suse.com>
(cherry picked from commit 2435f641e8936c9655638fc25c8829c053391e99)

diff --git a/package/Dockerfile b/package/Dockerfile
--- a/package/Dockerfile
+++ b/package/Dockerfile
@@ -1,3 +1,5 @@
+# syntax=docker/dockerfile:1.7.0
+
 FROM registry.suse.com/bci/bci-base:15.5
 
 # util-linux-systemd -> for `lsblk` command
@@ -7,5 +9,14 @@ RUN zypper -n rm container-suseconnect && \
     zypper -n install util-linux-systemd e2fsprogs iproute2 && \
     zypper -n clean -a && rm -rf /tmp/* /var/tmp/* /usr/share/doc/packages/*
 
-COPY bin/node-disk-manager /usr/bin/
+ARG TARGETPLATFORM
+
+RUN if [ "$TARGETPLATFORM" != "linux/amd64" ] && [ "$TARGETPLATFORM" != "linux/arm64" ]; then \
+    echo "Error: Unsupported TARGETPLATFORM: $TARGETPLATFORM" && \
+    exit 1; \
+    fi
+
+ENV ARCH=${TARGETPLATFORM#linux/}
+
+COPY bin/node-disk-manager-${ARCH} /usr/bin/node-disk-manager
 CMD ["node-disk-manager"]
